config/routes.rb
ApiDoc::Engine.routes.draw do
  match "*path", to: "documents#show", as: :api_doc_page
  root to: "documents#index", as: :api_doc_home
end

app/controllers/api_doc/application_controller.rb
module ApiDoc
  class ApplicationController < ::ApplicationController#ActionController::Base
  end
end

app/controllers/api_doc/documents_controller.rb
class ApiDoc::DocumentsController < ApiDoc::ApplicationController
  # layout "api_doc/application"

  def index
    # render text: "Yeah!"
  end

  def show
    render template: File.join("api_docs", params[:path])
  end

end

# <h1><%= @options[:path] %></h1>
# <h2>Example</h2>
# <p>URL: <%= @request.path_info %></p>
# <pre><code>
# <%= json %>
# </code></pre>

app/helpers/api_doc/application_helper.rb
module ApiDoc
  module ApplicationHelper
    
    def sidebar_links
      groups = {}
      # links = ""
      files = Dir.glob(File.join(ApiDoc::Config.view_path, "**", "*.html.erb")).sort
      files.each do |file|
        name = file.gsub(ApiDoc::Config.view_path, "")
        name.gsub!(".html.erb", "")
        name.gsub!(/^\//, "")
        groups[File.dirname(name)] ||= []
        groups[File.dirname(name)] << name
      #   links << "<li><a href='#{api_doc_page_path(path: name)}'>#{name}</a></li>"
      end
      html = ""
      groups.each do |group, names|
        html << "<li class='nav-header'>#{group}</li>"
        names.each do |name|
          display_name = name.gsub(group, "")
          Rails.logger.info display_name
          display_name.gsub!(/^\//, "")
          Rails.logger.info display_name
          display_name.gsub!(/(^[^\_]+)\_/, '\1 ')
          Rails.logger.info display_name
          display_name.gsub!(/\_\(/, " (")
          Rails.logger.info display_name
          html << "<li><a href='#{api_doc_page_path(path: name)}'>#{display_name.gsub("_", " ")}</a></li>"
        end
      end
      raw html
    end

    def tr(slug, *args)
      path = %w{api_doc page}
      no_slug_path = path.dup
      path << slug
      path << args
      no_slug_path << args
      path.flatten!
      no_slug_path.flatten!
      t(path.flatten.join("."), default: t(no_slug_path.join('.'), default: ""))
    end

  end
end

app/views/api_doc/shared/_footer.html.erb
<footer>
  <p>&copy; <%= Time.now.year %> - <%= t "api_doc.company_name" %></p>
</footer>

app/views/layouts/api_doc/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= ApiDoc::Config.doc_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <%= stylesheet_link_tag    "api_doc/application", :media => "all" %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "api_doc/application" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to("#{t 'api_doc.company_name'} #{ApiDoc::Config.doc_title}", api_doc_home_path, class: "brand") %>
          <%= render partial: "api_doc/shared/nav_bar" %>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <%= sidebar_links %>
<!--               <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li> -->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <%= render partial: "api_doc/shared/footer" %>

    </div><!--/.fluid-container-->

  </body>
</html>